# Generated by Django 5.1.4 on 2025-02-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_chatid_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatid',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
