# Generated by Django 5.1.4 on 2025-02-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatid_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatid',
            unique_together=set(),
        ),
    ]
