# Generated by Django 5.1.4 on 2025-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatid_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
