# Generated by Django 5.1.4 on 2025-01-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='CourseFeedback',
        ),
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_video_course', to='course.course'),
        ),
    ]
