# Generated by Django 5.1.4 on 2025-01-21 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_feedback_coursefeedback_course_course_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback_course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback_student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_video_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_video',
            field=models.FileField(blank=True, upload_to='course_video/'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_video_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_video_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
