# Generated by Django 5.1.4 on 2025-01-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_course_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeedback',
            name='feedback_course',
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='feedback_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_video/'),
        ),
    ]
