# Generated by Django 5.1.4 on 2025-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_category_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
