# Generated by Django 5.1.4 on 2025-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_category_status_course_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active'),
        ),
    ]
