# Generated by Django 5.1.4 on 2025-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursefeedback_status_coursevideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.FileField(default='', upload_to='course-thumbnail'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='course_video_thumbnail',
            field=models.FileField(default='', upload_to='course-video-thumbnail'),
        ),
    ]
