# Generated by Django 5.1.4 on 2025-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.FileField(blank=True, default='', null=True, upload_to='course-thumbnail'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='course_video_thumbnail',
            field=models.FileField(blank=True, default='', null=True, upload_to='course-video-thumbnail'),
        ),
    ]
