# Generated by Django 5.1.4 on 2025-02-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='teacher_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
