# Generated by Django 5.1.4 on 2025-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursefeedback_teacher_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
