# Generated by Django 5.1.4 on 2025-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepurchase',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
