# Generated by Django 5.1.4 on 2025-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_coursepurchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
