# Generated by Django 5.1.4 on 2025-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_coursepurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='teacher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
