# Generated by Django 5.1.4 on 2025-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_12th_marsheet_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='user_12th_marsheet_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_degree_certificate',
            field=models.FileField(blank=True, default='', null=True, upload_to='user_degree_certificate'),
        ),
    ]
