# Generated by Django 5.1.4 on 2025-02-18 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
