# Generated by Django 5.1.4 on 2025-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
