# Generated by Django 5.1.4 on 2025-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_razorpay_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_fund_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
