# Generated by Django 5.1.4 on 2025-02-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_issue', models.CharField(choices=[('Payment', 'Payment'), ('Website Design', 'Website Design'), ('User Interface Issue', 'User Interface Issue'), ('Slow Performance', 'Slow Performance'), ('Broken Links', 'Broken Links'), ('Login/Registration Issue', 'Login/Registration Issue'), ('Bug/Error', 'Bug/Error'), ('Feature Request', 'Feature Request'), ('Security Concern', 'Security Concern'), ('Other', 'Other')], default='Other', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=50)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
