# Generated by Django 5.1.4 on 2025-02-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0002_videoroom_duration_videoroom_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoroom',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='videoroom',
            old_name='start_date',
            new_name='start',
        ),
    ]
